/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * App Link lifecycle state
 */
@JsonAdapter(AppLinkState.Adapter.class)
public enum AppLinkState {
  
  PROVISIONING("PROVISIONING"),
  
  PROVISIONING_FAILED("PROVISIONING_FAILED"),
  
  PROVISIONED("PROVISIONED"),
  
  DEPROVISIONING("DEPROVISIONING"),
  
  DEPROVISIONING_FAILED("DEPROVISIONING_FAILED"),
  
  DEPROVISIONED("DEPROVISIONED"),
  
  REPROVISIONING("REPROVISIONING"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  AppLinkState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AppLinkState fromValue(String value) {
    for (AppLinkState b : AppLinkState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<AppLinkState> {
    @Override
    public void write(final JsonWriter jsonWriter, final AppLinkState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AppLinkState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AppLinkState.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AppLinkState.fromValue(value);
  }
}

