/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Arrays of objects containing latency data for the specified metros
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class ConnectedMetro {
  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  @javax.annotation.Nullable
  private String href;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nullable
  private String code;

  public static final String SERIALIZED_NAME_AVG_LATENCY = "avgLatency";
  @SerializedName(SERIALIZED_NAME_AVG_LATENCY)
  @javax.annotation.Nullable
  private BigDecimal avgLatency;

  public static final String SERIALIZED_NAME_REMOTE_V_C_BANDWIDTH_MAX = "remoteVCBandwidthMax";
  @SerializedName(SERIALIZED_NAME_REMOTE_V_C_BANDWIDTH_MAX)
  @javax.annotation.Nullable
  private Long remoteVCBandwidthMax;

  public ConnectedMetro() {
  }

  public ConnectedMetro href(@javax.annotation.Nullable String href) {
    this.href = href;
    return this;
  }

  /**
   * The Canonical URL at which the resource resides.
   * @return href
   */
  @javax.annotation.Nullable
  public String getHref() {
    return href;
  }

  public void setHref(@javax.annotation.Nullable String href) {
    this.href = href;
  }


  public ConnectedMetro code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Code assigned to an Equinix International Business Exchange (IBX) data center in a specified metropolitan area.
   * @return code
   */
  @javax.annotation.Nullable
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public ConnectedMetro avgLatency(@javax.annotation.Nullable BigDecimal avgLatency) {
    this.avgLatency = avgLatency;
    return this;
  }

  /**
   * Average latency (in milliseconds[ms]) between two specified metros.
   * @return avgLatency
   */
  @javax.annotation.Nullable
  public BigDecimal getAvgLatency() {
    return avgLatency;
  }

  public void setAvgLatency(@javax.annotation.Nullable BigDecimal avgLatency) {
    this.avgLatency = avgLatency;
  }


  public ConnectedMetro remoteVCBandwidthMax(@javax.annotation.Nullable Long remoteVCBandwidthMax) {
    this.remoteVCBandwidthMax = remoteVCBandwidthMax;
    return this;
  }

  /**
   * This field holds the Max Connection speed with connected metros
   * @return remoteVCBandwidthMax
   */
  @javax.annotation.Nullable
  public Long getRemoteVCBandwidthMax() {
    return remoteVCBandwidthMax;
  }

  public void setRemoteVCBandwidthMax(@javax.annotation.Nullable Long remoteVCBandwidthMax) {
    this.remoteVCBandwidthMax = remoteVCBandwidthMax;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectedMetro connectedMetro = (ConnectedMetro) o;
    return Objects.equals(this.href, connectedMetro.href) &&
        Objects.equals(this.code, connectedMetro.code) &&
        Objects.equals(this.avgLatency, connectedMetro.avgLatency) &&
        Objects.equals(this.remoteVCBandwidthMax, connectedMetro.remoteVCBandwidthMax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, code, avgLatency, remoteVCBandwidthMax);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectedMetro {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    avgLatency: ").append(toIndentedString(avgLatency)).append("\n");
    sb.append("    remoteVCBandwidthMax: ").append(toIndentedString(remoteVCBandwidthMax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("href", "code", "avgLatency", "remoteVCBandwidthMax"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConnectedMetro
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConnectedMetro.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ConnectedMetro is not found in the empty JSON string", ConnectedMetro.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConnectedMetro.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConnectedMetro` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("href") != null && !jsonObj.get("href").isJsonNull()) && !jsonObj.get("href").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `href` to be a primitive type in the JSON string but got `%s`", jsonObj.get("href").toString()));
      }
      if ((jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull()) && !jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectedMetro.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectedMetro' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectedMetro> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectedMetro.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectedMetro>() {
           @Override
           public void write(JsonWriter out, ConnectedMetro value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectedMetro read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConnectedMetro given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConnectedMetro
   * @throws IOException if the JSON string is invalid with respect to ConnectedMetro
   */
  public static ConnectedMetro fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectedMetro.class);
  }

  /**
   * Convert an instance of ConnectedMetro to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

