/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.EquinixStatus;
import com.equinix.sdk.fabricv4.model.Error;
import com.equinix.sdk.fabricv4.model.ProviderStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Connection type-specific operational data
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class ConnectionOperation {
  public static final String SERIALIZED_NAME_PROVIDER_STATUS = "providerStatus";
  @SerializedName(SERIALIZED_NAME_PROVIDER_STATUS)
  @javax.annotation.Nullable
  private ProviderStatus providerStatus;

  public static final String SERIALIZED_NAME_EQUINIX_STATUS = "equinixStatus";
  @SerializedName(SERIALIZED_NAME_EQUINIX_STATUS)
  @javax.annotation.Nullable
  private EquinixStatus equinixStatus;

  /**
   * Connection operational status
   */
  @JsonAdapter(OperationalStatusEnum.Adapter.class)
  public enum OperationalStatusEnum {
    UP("UP"),
    
    DOWN("DOWN");

    private String value;

    OperationalStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperationalStatusEnum fromValue(String value) {
      for (OperationalStatusEnum b : OperationalStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OperationalStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperationalStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperationalStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OperationalStatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OperationalStatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_OPERATIONAL_STATUS = "operationalStatus";
  @SerializedName(SERIALIZED_NAME_OPERATIONAL_STATUS)
  @javax.annotation.Nullable
  private OperationalStatusEnum operationalStatus;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  @javax.annotation.Nullable
  private List<Error> errors = new ArrayList<>();

  public static final String SERIALIZED_NAME_OP_STATUS_CHANGED_AT = "opStatusChangedAt";
  @SerializedName(SERIALIZED_NAME_OP_STATUS_CHANGED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime opStatusChangedAt;

  public ConnectionOperation() {
  }

  public ConnectionOperation providerStatus(@javax.annotation.Nullable ProviderStatus providerStatus) {
    this.providerStatus = providerStatus;
    return this;
  }

  /**
   * Get providerStatus
   * @return providerStatus
   */
  @javax.annotation.Nullable
  public ProviderStatus getProviderStatus() {
    return providerStatus;
  }

  public void setProviderStatus(@javax.annotation.Nullable ProviderStatus providerStatus) {
    this.providerStatus = providerStatus;
  }


  public ConnectionOperation equinixStatus(@javax.annotation.Nullable EquinixStatus equinixStatus) {
    this.equinixStatus = equinixStatus;
    return this;
  }

  /**
   * Get equinixStatus
   * @return equinixStatus
   */
  @javax.annotation.Nullable
  public EquinixStatus getEquinixStatus() {
    return equinixStatus;
  }

  public void setEquinixStatus(@javax.annotation.Nullable EquinixStatus equinixStatus) {
    this.equinixStatus = equinixStatus;
  }


  public ConnectionOperation operationalStatus(@javax.annotation.Nullable OperationalStatusEnum operationalStatus) {
    this.operationalStatus = operationalStatus;
    return this;
  }

  /**
   * Connection operational status
   * @return operationalStatus
   */
  @javax.annotation.Nullable
  public OperationalStatusEnum getOperationalStatus() {
    return operationalStatus;
  }

  public void setOperationalStatus(@javax.annotation.Nullable OperationalStatusEnum operationalStatus) {
    this.operationalStatus = operationalStatus;
  }


  public ConnectionOperation errors(@javax.annotation.Nullable List<Error> errors) {
    this.errors = errors;
    return this;
  }

  public ConnectionOperation addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nullable
  public List<Error> getErrors() {
    return errors;
  }

  public void setErrors(@javax.annotation.Nullable List<Error> errors) {
    this.errors = errors;
  }


  public ConnectionOperation opStatusChangedAt(@javax.annotation.Nullable OffsetDateTime opStatusChangedAt) {
    this.opStatusChangedAt = opStatusChangedAt;
    return this;
  }

  /**
   * When connection transitioned into current operational status
   * @return opStatusChangedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getOpStatusChangedAt() {
    return opStatusChangedAt;
  }

  public void setOpStatusChangedAt(@javax.annotation.Nullable OffsetDateTime opStatusChangedAt) {
    this.opStatusChangedAt = opStatusChangedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionOperation connectionOperation = (ConnectionOperation) o;
    return Objects.equals(this.providerStatus, connectionOperation.providerStatus) &&
        Objects.equals(this.equinixStatus, connectionOperation.equinixStatus) &&
        Objects.equals(this.operationalStatus, connectionOperation.operationalStatus) &&
        Objects.equals(this.errors, connectionOperation.errors) &&
        Objects.equals(this.opStatusChangedAt, connectionOperation.opStatusChangedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerStatus, equinixStatus, operationalStatus, errors, opStatusChangedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionOperation {\n");
    sb.append("    providerStatus: ").append(toIndentedString(providerStatus)).append("\n");
    sb.append("    equinixStatus: ").append(toIndentedString(equinixStatus)).append("\n");
    sb.append("    operationalStatus: ").append(toIndentedString(operationalStatus)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    opStatusChangedAt: ").append(toIndentedString(opStatusChangedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("providerStatus", "equinixStatus", "operationalStatus", "errors", "opStatusChangedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConnectionOperation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConnectionOperation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ConnectionOperation is not found in the empty JSON string", ConnectionOperation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConnectionOperation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConnectionOperation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `providerStatus`
      if (jsonObj.get("providerStatus") != null && !jsonObj.get("providerStatus").isJsonNull()) {
        ProviderStatus.validateJsonElement(jsonObj.get("providerStatus"));
      }
      // validate the optional field `equinixStatus`
      if (jsonObj.get("equinixStatus") != null && !jsonObj.get("equinixStatus").isJsonNull()) {
        EquinixStatus.validateJsonElement(jsonObj.get("equinixStatus"));
      }
      if ((jsonObj.get("operationalStatus") != null && !jsonObj.get("operationalStatus").isJsonNull()) && !jsonObj.get("operationalStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `operationalStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("operationalStatus").toString()));
      }
      // validate the optional field `operationalStatus`
      if (jsonObj.get("operationalStatus") != null && !jsonObj.get("operationalStatus").isJsonNull()) {
        OperationalStatusEnum.validateJsonElement(jsonObj.get("operationalStatus"));
      }
      if (jsonObj.get("errors") != null && !jsonObj.get("errors").isJsonNull()) {
        JsonArray jsonArrayerrors = jsonObj.getAsJsonArray("errors");
        if (jsonArrayerrors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("errors").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `errors` to be an array in the JSON string but got `%s`", jsonObj.get("errors").toString()));
          }

          // validate the optional field `errors` (array)
          for (int i = 0; i < jsonArrayerrors.size(); i++) {
            Error.validateJsonElement(jsonArrayerrors.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectionOperation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectionOperation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectionOperation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectionOperation.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectionOperation>() {
           @Override
           public void write(JsonWriter out, ConnectionOperation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectionOperation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConnectionOperation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConnectionOperation
   * @throws IOException if the JSON string is invalid with respect to ConnectionOperation
   */
  public static ConnectionOperation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectionOperation.class);
  }

  /**
   * Convert an instance of ConnectionOperation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

