/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.GatewayType;
import com.equinix.sdk.fabricv4.model.Order;
import com.equinix.sdk.fabricv4.model.Project;
import com.equinix.sdk.fabricv4.model.Router;
import com.equinix.sdk.fabricv4.model.SimplifiedAccount;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Create Gateway
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class GatewayPostRequest {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private GatewayType type;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_BANDWIDTH = "bandwidth";
  @SerializedName(SERIALIZED_NAME_BANDWIDTH)
  @javax.annotation.Nonnull
  private Integer bandwidth;

  public static final String SERIALIZED_NAME_LOCAL_ASN = "localAsn";
  @SerializedName(SERIALIZED_NAME_LOCAL_ASN)
  @javax.annotation.Nonnull
  private Integer localAsn;

  public static final String SERIALIZED_NAME_ROUTER = "router";
  @SerializedName(SERIALIZED_NAME_ROUTER)
  @javax.annotation.Nonnull
  private Router router;

  public static final String SERIALIZED_NAME_HA_ENABLED = "haEnabled";
  @SerializedName(SERIALIZED_NAME_HA_ENABLED)
  @javax.annotation.Nullable
  private Boolean haEnabled = false;

  public static final String SERIALIZED_NAME_ACCOUNT = "account";
  @SerializedName(SERIALIZED_NAME_ACCOUNT)
  @javax.annotation.Nonnull
  private SimplifiedAccount account;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  @javax.annotation.Nonnull
  private Project project;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  @javax.annotation.Nullable
  private Order order;

  public GatewayPostRequest() {
  }

  public GatewayPostRequest type(@javax.annotation.Nonnull GatewayType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public GatewayType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull GatewayType type) {
    this.type = type;
  }


  public GatewayPostRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Customer-provided Gateway name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public GatewayPostRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Customer-provided Gateway description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GatewayPostRequest bandwidth(@javax.annotation.Nonnull Integer bandwidth) {
    this.bandwidth = bandwidth;
    return this;
  }

  /**
   * Gateway bandwidth in Mbps
   * minimum: 0
   * maximum: 10000
   * @return bandwidth
   */
  @javax.annotation.Nonnull
  public Integer getBandwidth() {
    return bandwidth;
  }

  public void setBandwidth(@javax.annotation.Nonnull Integer bandwidth) {
    this.bandwidth = bandwidth;
  }


  public GatewayPostRequest localAsn(@javax.annotation.Nonnull Integer localAsn) {
    this.localAsn = localAsn;
    return this;
  }

  /**
   * Gateway local Autonomous System Number
   * @return localAsn
   */
  @javax.annotation.Nonnull
  public Integer getLocalAsn() {
    return localAsn;
  }

  public void setLocalAsn(@javax.annotation.Nonnull Integer localAsn) {
    this.localAsn = localAsn;
  }


  public GatewayPostRequest router(@javax.annotation.Nonnull Router router) {
    this.router = router;
    return this;
  }

  /**
   * Get router
   * @return router
   */
  @javax.annotation.Nonnull
  public Router getRouter() {
    return router;
  }

  public void setRouter(@javax.annotation.Nonnull Router router) {
    this.router = router;
  }


  public GatewayPostRequest haEnabled(@javax.annotation.Nullable Boolean haEnabled) {
    this.haEnabled = haEnabled;
    return this;
  }

  /**
   * High availability enabled
   * @return haEnabled
   */
  @javax.annotation.Nullable
  public Boolean getHaEnabled() {
    return haEnabled;
  }

  public void setHaEnabled(@javax.annotation.Nullable Boolean haEnabled) {
    this.haEnabled = haEnabled;
  }


  public GatewayPostRequest account(@javax.annotation.Nonnull SimplifiedAccount account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nonnull
  public SimplifiedAccount getAccount() {
    return account;
  }

  public void setAccount(@javax.annotation.Nonnull SimplifiedAccount account) {
    this.account = account;
  }


  public GatewayPostRequest project(@javax.annotation.Nonnull Project project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nonnull
  public Project getProject() {
    return project;
  }

  public void setProject(@javax.annotation.Nonnull Project project) {
    this.project = project;
  }


  public GatewayPostRequest order(@javax.annotation.Nullable Order order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   */
  @javax.annotation.Nullable
  public Order getOrder() {
    return order;
  }

  public void setOrder(@javax.annotation.Nullable Order order) {
    this.order = order;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GatewayPostRequest instance itself
   */
  public GatewayPostRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayPostRequest gatewayPostRequest = (GatewayPostRequest) o;
    return Objects.equals(this.type, gatewayPostRequest.type) &&
        Objects.equals(this.name, gatewayPostRequest.name) &&
        Objects.equals(this.description, gatewayPostRequest.description) &&
        Objects.equals(this.bandwidth, gatewayPostRequest.bandwidth) &&
        Objects.equals(this.localAsn, gatewayPostRequest.localAsn) &&
        Objects.equals(this.router, gatewayPostRequest.router) &&
        Objects.equals(this.haEnabled, gatewayPostRequest.haEnabled) &&
        Objects.equals(this.account, gatewayPostRequest.account) &&
        Objects.equals(this.project, gatewayPostRequest.project) &&
        Objects.equals(this.order, gatewayPostRequest.order)&&
        Objects.equals(this.additionalProperties, gatewayPostRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, description, bandwidth, localAsn, router, haEnabled, account, project, order, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayPostRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    bandwidth: ").append(toIndentedString(bandwidth)).append("\n");
    sb.append("    localAsn: ").append(toIndentedString(localAsn)).append("\n");
    sb.append("    router: ").append(toIndentedString(router)).append("\n");
    sb.append("    haEnabled: ").append(toIndentedString(haEnabled)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "name", "description", "bandwidth", "localAsn", "router", "haEnabled", "account", "project", "order"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "name", "bandwidth", "localAsn", "router", "account", "project"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GatewayPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GatewayPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GatewayPostRequest is not found in the empty JSON string", GatewayPostRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GatewayPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `type`
      GatewayType.validateJsonElement(jsonObj.get("type"));
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // validate the required field `router`
      Router.validateJsonElement(jsonObj.get("router"));
      // validate the required field `account`
      SimplifiedAccount.validateJsonElement(jsonObj.get("account"));
      // validate the required field `project`
      Project.validateJsonElement(jsonObj.get("project"));
      // validate the optional field `order`
      if (jsonObj.get("order") != null && !jsonObj.get("order").isJsonNull()) {
        Order.validateJsonElement(jsonObj.get("order"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GatewayPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GatewayPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GatewayPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GatewayPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GatewayPostRequest>() {
           @Override
           public void write(JsonWriter out, GatewayPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GatewayPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GatewayPostRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GatewayPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GatewayPostRequest
   * @throws IOException if the JSON string is invalid with respect to GatewayPostRequest
   */
  public static GatewayPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GatewayPostRequest.class);
  }

  /**
   * Convert an instance of GatewayPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

