/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.HopProbes;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Hop
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Hop {
  public static final String SERIALIZED_NAME_HOP = "hop";
  @SerializedName(SERIALIZED_NAME_HOP)
  @javax.annotation.Nullable
  private Integer hop;

  public static final String SERIALIZED_NAME_PROBES = "probes";
  @SerializedName(SERIALIZED_NAME_PROBES)
  @javax.annotation.Nullable
  private List<HopProbes> probes = new ArrayList<>();

  public Hop() {
  }

  public Hop hop(@javax.annotation.Nullable Integer hop) {
    this.hop = hop;
    return this;
  }

  /**
   * Get hop
   * @return hop
   */
  @javax.annotation.Nullable
  public Integer getHop() {
    return hop;
  }

  public void setHop(@javax.annotation.Nullable Integer hop) {
    this.hop = hop;
  }


  public Hop probes(@javax.annotation.Nullable List<HopProbes> probes) {
    this.probes = probes;
    return this;
  }

  public Hop addProbesItem(HopProbes probesItem) {
    if (this.probes == null) {
      this.probes = new ArrayList<>();
    }
    this.probes.add(probesItem);
    return this;
  }

  /**
   * Get probes
   * @return probes
   */
  @javax.annotation.Nullable
  public List<HopProbes> getProbes() {
    return probes;
  }

  public void setProbes(@javax.annotation.Nullable List<HopProbes> probes) {
    this.probes = probes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hop hop = (Hop) o;
    return Objects.equals(this.hop, hop.hop) &&
        Objects.equals(this.probes, hop.probes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hop, probes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hop {\n");
    sb.append("    hop: ").append(toIndentedString(hop)).append("\n");
    sb.append("    probes: ").append(toIndentedString(probes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("hop", "probes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Hop
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Hop.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Hop is not found in the empty JSON string", Hop.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Hop.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Hop` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("probes") != null && !jsonObj.get("probes").isJsonNull()) {
        JsonArray jsonArrayprobes = jsonObj.getAsJsonArray("probes");
        if (jsonArrayprobes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("probes").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `probes` to be an array in the JSON string but got `%s`", jsonObj.get("probes").toString()));
          }

          // validate the optional field `probes` (array)
          for (int i = 0; i < jsonArrayprobes.size(); i++) {
            HopProbes.validateJsonElement(jsonArrayprobes.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Hop.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Hop' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Hop> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Hop.class));

       return (TypeAdapter<T>) new TypeAdapter<Hop>() {
           @Override
           public void write(JsonWriter out, Hop value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Hop read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Hop given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Hop
   * @throws IOException if the JSON string is invalid with respect to Hop
   */
  public static Hop fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Hop.class);
  }

  /**
   * Convert an instance of Hop to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

