/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * InternetAccessPeeringIpv4
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class InternetAccessPeeringIpv4 {
  public static final String SERIALIZED_NAME_PREFIX = "prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  @javax.annotation.Nullable
  private String prefix;

  public static final String SERIALIZED_NAME_PREFIX_LENGTH = "prefixLength";
  @SerializedName(SERIALIZED_NAME_PREFIX_LENGTH)
  @javax.annotation.Nullable
  private Integer prefixLength;

  public static final String SERIALIZED_NAME_EQUINIX_PEER_IP = "equinixPeerIp";
  @SerializedName(SERIALIZED_NAME_EQUINIX_PEER_IP)
  @javax.annotation.Nullable
  private String equinixPeerIp;

  public static final String SERIALIZED_NAME_CUSTOMER_PEER_IP = "customerPeerIp";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_PEER_IP)
  @javax.annotation.Nullable
  private String customerPeerIp;

  public static final String SERIALIZED_NAME_EQUINIX_VRRP_IP = "equinixVrrpIp";
  @SerializedName(SERIALIZED_NAME_EQUINIX_VRRP_IP)
  @javax.annotation.Nullable
  private String equinixVrrpIp;

  public static final String SERIALIZED_NAME_CUSTOMER_VRRP_IP = "customerVrrpIp";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_VRRP_IP)
  @javax.annotation.Nullable
  private String customerVrrpIp;

  public InternetAccessPeeringIpv4() {
  }

  public InternetAccessPeeringIpv4 prefix(@javax.annotation.Nullable String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * IPv4 prefix for the peering connection
   * @return prefix
   */
  @javax.annotation.Nullable
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(@javax.annotation.Nullable String prefix) {
    this.prefix = prefix;
  }


  public InternetAccessPeeringIpv4 prefixLength(@javax.annotation.Nullable Integer prefixLength) {
    this.prefixLength = prefixLength;
    return this;
  }

  /**
   * Determines the size of subnet
   * minimum: 1
   * maximum: 32
   * @return prefixLength
   */
  @javax.annotation.Nullable
  public Integer getPrefixLength() {
    return prefixLength;
  }

  public void setPrefixLength(@javax.annotation.Nullable Integer prefixLength) {
    this.prefixLength = prefixLength;
  }


  public InternetAccessPeeringIpv4 equinixPeerIp(@javax.annotation.Nullable String equinixPeerIp) {
    this.equinixPeerIp = equinixPeerIp;
    return this;
  }

  /**
   * IPv4 peering IP address for Equinix side
   * @return equinixPeerIp
   */
  @javax.annotation.Nullable
  public String getEquinixPeerIp() {
    return equinixPeerIp;
  }

  public void setEquinixPeerIp(@javax.annotation.Nullable String equinixPeerIp) {
    this.equinixPeerIp = equinixPeerIp;
  }


  public InternetAccessPeeringIpv4 customerPeerIp(@javax.annotation.Nullable String customerPeerIp) {
    this.customerPeerIp = customerPeerIp;
    return this;
  }

  /**
   * IPv4 peering IP address for customer side
   * @return customerPeerIp
   */
  @javax.annotation.Nullable
  public String getCustomerPeerIp() {
    return customerPeerIp;
  }

  public void setCustomerPeerIp(@javax.annotation.Nullable String customerPeerIp) {
    this.customerPeerIp = customerPeerIp;
  }


  public InternetAccessPeeringIpv4 equinixVrrpIp(@javax.annotation.Nullable String equinixVrrpIp) {
    this.equinixVrrpIp = equinixVrrpIp;
    return this;
  }

  /**
   * IPv4 address for Equinix VRRP IP
   * @return equinixVrrpIp
   */
  @javax.annotation.Nullable
  public String getEquinixVrrpIp() {
    return equinixVrrpIp;
  }

  public void setEquinixVrrpIp(@javax.annotation.Nullable String equinixVrrpIp) {
    this.equinixVrrpIp = equinixVrrpIp;
  }


  public InternetAccessPeeringIpv4 customerVrrpIp(@javax.annotation.Nullable String customerVrrpIp) {
    this.customerVrrpIp = customerVrrpIp;
    return this;
  }

  /**
   * IPv4 address for customer VRRP IP
   * @return customerVrrpIp
   */
  @javax.annotation.Nullable
  public String getCustomerVrrpIp() {
    return customerVrrpIp;
  }

  public void setCustomerVrrpIp(@javax.annotation.Nullable String customerVrrpIp) {
    this.customerVrrpIp = customerVrrpIp;
  }


  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InternetAccessPeeringIpv4 instance itself
   */
  public InternetAccessPeeringIpv4 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternetAccessPeeringIpv4 internetAccessPeeringIpv4 = (InternetAccessPeeringIpv4) o;
    return Objects.equals(this.prefix, internetAccessPeeringIpv4.prefix) &&
        Objects.equals(this.prefixLength, internetAccessPeeringIpv4.prefixLength) &&
        Objects.equals(this.equinixPeerIp, internetAccessPeeringIpv4.equinixPeerIp) &&
        Objects.equals(this.customerPeerIp, internetAccessPeeringIpv4.customerPeerIp) &&
        Objects.equals(this.equinixVrrpIp, internetAccessPeeringIpv4.equinixVrrpIp) &&
        Objects.equals(this.customerVrrpIp, internetAccessPeeringIpv4.customerVrrpIp)&&
        Objects.equals(this.additionalProperties, internetAccessPeeringIpv4.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prefix, prefixLength, equinixPeerIp, customerPeerIp, equinixVrrpIp, customerVrrpIp, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternetAccessPeeringIpv4 {\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    prefixLength: ").append(toIndentedString(prefixLength)).append("\n");
    sb.append("    equinixPeerIp: ").append(toIndentedString(equinixPeerIp)).append("\n");
    sb.append("    customerPeerIp: ").append(toIndentedString(customerPeerIp)).append("\n");
    sb.append("    equinixVrrpIp: ").append(toIndentedString(equinixVrrpIp)).append("\n");
    sb.append("    customerVrrpIp: ").append(toIndentedString(customerVrrpIp)).append("\n");

    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");

    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("prefix", "prefixLength", "equinixPeerIp", "customerPeerIp", "equinixVrrpIp", "customerVrrpIp"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternetAccessPeeringIpv4
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternetAccessPeeringIpv4.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in InternetAccessPeeringIpv4 is not found in the empty JSON string", InternetAccessPeeringIpv4.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("prefix") != null && !jsonObj.get("prefix").isJsonNull()) && !jsonObj.get("prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prefix").toString()));
      }
      if ((jsonObj.get("equinixPeerIp") != null && !jsonObj.get("equinixPeerIp").isJsonNull()) && !jsonObj.get("equinixPeerIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `equinixPeerIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("equinixPeerIp").toString()));
      }
      if ((jsonObj.get("customerPeerIp") != null && !jsonObj.get("customerPeerIp").isJsonNull()) && !jsonObj.get("customerPeerIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `customerPeerIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerPeerIp").toString()));
      }
      if ((jsonObj.get("equinixVrrpIp") != null && !jsonObj.get("equinixVrrpIp").isJsonNull()) && !jsonObj.get("equinixVrrpIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `equinixVrrpIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("equinixVrrpIp").toString()));
      }
      if ((jsonObj.get("customerVrrpIp") != null && !jsonObj.get("customerVrrpIp").isJsonNull()) && !jsonObj.get("customerVrrpIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `customerVrrpIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerVrrpIp").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InternetAccessPeeringIpv4.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InternetAccessPeeringIpv4' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InternetAccessPeeringIpv4> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InternetAccessPeeringIpv4.class));

       return (TypeAdapter<T>) new TypeAdapter<InternetAccessPeeringIpv4>() {
           @Override
           public void write(JsonWriter out, InternetAccessPeeringIpv4 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InternetAccessPeeringIpv4 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             InternetAccessPeeringIpv4 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InternetAccessPeeringIpv4 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternetAccessPeeringIpv4
   * @throws IOException if the JSON string is invalid with respect to InternetAccessPeeringIpv4
   */
  public static InternetAccessPeeringIpv4 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternetAccessPeeringIpv4.class);
  }

  /**
   * Convert an instance of InternetAccessPeeringIpv4 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

