/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.InternetAccessConnectionBgpRequest;
import com.equinix.sdk.fabricv4.model.InternetAccessCustomerAsnRange;
import com.equinix.sdk.fabricv4.model.InternetAccessCustomerRouteRequest;
import com.equinix.sdk.fabricv4.model.InternetAccessExportPolicy;
import com.equinix.sdk.fabricv4.model.InternetAccessRoutingProtocolRequest;
import com.equinix.sdk.fabricv4.model.InternetAccessRoutingProtocolType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * InternetAccessRoutingProtocolBgpRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class InternetAccessRoutingProtocolBgpRequest extends InternetAccessRoutingProtocolRequest {
  public static final String SERIALIZED_NAME_CONNECTIONS = "connections";
  @SerializedName(SERIALIZED_NAME_CONNECTIONS)
  @javax.annotation.Nonnull
  private List<InternetAccessConnectionBgpRequest> connections = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPORT_POLICY = "exportPolicy";
  @SerializedName(SERIALIZED_NAME_EXPORT_POLICY)
  @javax.annotation.Nonnull
  private InternetAccessExportPolicy exportPolicy;

  public static final String SERIALIZED_NAME_CUSTOMER_ASN = "customerAsn";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ASN)
  @javax.annotation.Nullable
  private Long customerAsn;

  public static final String SERIALIZED_NAME_BGP_AUTH_KEY = "bgpAuthKey";
  @SerializedName(SERIALIZED_NAME_BGP_AUTH_KEY)
  @javax.annotation.Nullable
  private String bgpAuthKey;

  public static final String SERIALIZED_NAME_CUSTOMER_ASN_RANGE = "customerAsnRange";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ASN_RANGE)
  @javax.annotation.Nullable
  private InternetAccessCustomerAsnRange customerAsnRange;

  public InternetAccessRoutingProtocolBgpRequest() {
  }

  public InternetAccessRoutingProtocolBgpRequest connections(@javax.annotation.Nonnull List<InternetAccessConnectionBgpRequest> connections) {
    this.connections = connections;
    return this;
  }

  public InternetAccessRoutingProtocolBgpRequest addConnectionsItem(InternetAccessConnectionBgpRequest connectionsItem) {
    if (this.connections == null) {
      this.connections = new ArrayList<>();
    }
    this.connections.add(connectionsItem);
    return this;
  }

  /**
   * Get connections
   * @return connections
   */
  @javax.annotation.Nonnull
  public List<InternetAccessConnectionBgpRequest> getConnections() {
    return connections;
  }

  public void setConnections(@javax.annotation.Nonnull List<InternetAccessConnectionBgpRequest> connections) {
    this.connections = connections;
  }


  public InternetAccessRoutingProtocolBgpRequest exportPolicy(@javax.annotation.Nonnull InternetAccessExportPolicy exportPolicy) {
    this.exportPolicy = exportPolicy;
    return this;
  }

  /**
   * Get exportPolicy
   * @return exportPolicy
   */
  @javax.annotation.Nonnull
  public InternetAccessExportPolicy getExportPolicy() {
    return exportPolicy;
  }

  public void setExportPolicy(@javax.annotation.Nonnull InternetAccessExportPolicy exportPolicy) {
    this.exportPolicy = exportPolicy;
  }


  public InternetAccessRoutingProtocolBgpRequest customerAsn(@javax.annotation.Nullable Long customerAsn) {
    this.customerAsn = customerAsn;
    return this;
  }

  /**
   * Customer ASN. Valid range is 1-64495 or 65536-4199999999.
   * @return customerAsn
   */
  @javax.annotation.Nullable
  public Long getCustomerAsn() {
    return customerAsn;
  }

  public void setCustomerAsn(@javax.annotation.Nullable Long customerAsn) {
    this.customerAsn = customerAsn;
  }


  public InternetAccessRoutingProtocolBgpRequest bgpAuthKey(@javax.annotation.Nullable String bgpAuthKey) {
    this.bgpAuthKey = bgpAuthKey;
    return this;
  }

  /**
   * BGP authentication key
   * @return bgpAuthKey
   */
  @javax.annotation.Nullable
  public String getBgpAuthKey() {
    return bgpAuthKey;
  }

  public void setBgpAuthKey(@javax.annotation.Nullable String bgpAuthKey) {
    this.bgpAuthKey = bgpAuthKey;
  }


  public InternetAccessRoutingProtocolBgpRequest customerAsnRange(@javax.annotation.Nullable InternetAccessCustomerAsnRange customerAsnRange) {
    this.customerAsnRange = customerAsnRange;
    return this;
  }

  /**
   * Get customerAsnRange
   * @return customerAsnRange
   */
  @javax.annotation.Nullable
  public InternetAccessCustomerAsnRange getCustomerAsnRange() {
    return customerAsnRange;
  }

  public void setCustomerAsnRange(@javax.annotation.Nullable InternetAccessCustomerAsnRange customerAsnRange) {
    this.customerAsnRange = customerAsnRange;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternetAccessRoutingProtocolBgpRequest internetAccessRoutingProtocolBgpRequest = (InternetAccessRoutingProtocolBgpRequest) o;
    return Objects.equals(this.connections, internetAccessRoutingProtocolBgpRequest.connections) &&
        Objects.equals(this.exportPolicy, internetAccessRoutingProtocolBgpRequest.exportPolicy) &&
        Objects.equals(this.customerAsn, internetAccessRoutingProtocolBgpRequest.customerAsn) &&
        Objects.equals(this.bgpAuthKey, internetAccessRoutingProtocolBgpRequest.bgpAuthKey) &&
        Objects.equals(this.customerAsnRange, internetAccessRoutingProtocolBgpRequest.customerAsnRange) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connections, exportPolicy, customerAsn, bgpAuthKey, customerAsnRange, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternetAccessRoutingProtocolBgpRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
    sb.append("    exportPolicy: ").append(toIndentedString(exportPolicy)).append("\n");
    sb.append("    customerAsn: ").append(toIndentedString(customerAsn)).append("\n");
    sb.append("    bgpAuthKey: ").append(toIndentedString(bgpAuthKey)).append("\n");
    sb.append("    customerAsnRange: ").append(toIndentedString(customerAsnRange)).append("\n");

    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "customerRoutes", "connections", "exportPolicy", "customerAsn", "bgpAuthKey", "customerAsnRange"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("connections", "exportPolicy", "type", "customerRoutes"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternetAccessRoutingProtocolBgpRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternetAccessRoutingProtocolBgpRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in InternetAccessRoutingProtocolBgpRequest is not found in the empty JSON string", InternetAccessRoutingProtocolBgpRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InternetAccessRoutingProtocolBgpRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("connections").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `connections` to be an array in the JSON string but got `%s`", jsonObj.get("connections").toString()));
      }

      JsonArray jsonArrayconnections = jsonObj.getAsJsonArray("connections");
      // validate the required field `connections` (array)
      for (int i = 0; i < jsonArrayconnections.size(); i++) {
        InternetAccessConnectionBgpRequest.validateJsonElement(jsonArrayconnections.get(i));
      };
      // validate the required field `exportPolicy`
      InternetAccessExportPolicy.validateJsonElement(jsonObj.get("exportPolicy"));
      if ((jsonObj.get("bgpAuthKey") != null && !jsonObj.get("bgpAuthKey").isJsonNull()) && !jsonObj.get("bgpAuthKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `bgpAuthKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bgpAuthKey").toString()));
      }
      // validate the optional field `customerAsnRange`
      if (jsonObj.get("customerAsnRange") != null && !jsonObj.get("customerAsnRange").isJsonNull()) {
        InternetAccessCustomerAsnRange.validateJsonElement(jsonObj.get("customerAsnRange"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InternetAccessRoutingProtocolBgpRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InternetAccessRoutingProtocolBgpRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InternetAccessRoutingProtocolBgpRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InternetAccessRoutingProtocolBgpRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<InternetAccessRoutingProtocolBgpRequest>() {
           @Override
           public void write(JsonWriter out, InternetAccessRoutingProtocolBgpRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InternetAccessRoutingProtocolBgpRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             InternetAccessRoutingProtocolBgpRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InternetAccessRoutingProtocolBgpRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternetAccessRoutingProtocolBgpRequest
   * @throws IOException if the JSON string is invalid with respect to InternetAccessRoutingProtocolBgpRequest
   */
  public static InternetAccessRoutingProtocolBgpRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternetAccessRoutingProtocolBgpRequest.class);
  }

  /**
   * Convert an instance of InternetAccessRoutingProtocolBgpRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

