/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Allowed patch operations.
 */
@JsonAdapter(InternetAccessPatchOperationUpdateAllowedOp.Adapter.class)
public enum InternetAccessPatchOperationUpdateAllowedOp {
  
  REPLACE("replace"),
  
  ADD("add"),
  
  REMOVE("remove");

  private String value;

  InternetAccessPatchOperationUpdateAllowedOp(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static InternetAccessPatchOperationUpdateAllowedOp fromValue(String value) {
    for (InternetAccessPatchOperationUpdateAllowedOp b : InternetAccessPatchOperationUpdateAllowedOp.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<InternetAccessPatchOperationUpdateAllowedOp> {
    @Override
    public void write(final JsonWriter jsonWriter, final InternetAccessPatchOperationUpdateAllowedOp enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public InternetAccessPatchOperationUpdateAllowedOp read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return InternetAccessPatchOperationUpdateAllowedOp.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    InternetAccessPatchOperationUpdateAllowedOp.fromValue(value);
  }
}

