/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.InternetAccessConnection;
import com.equinix.sdk.fabricv4.model.InternetAccessCustomerRoute;
import com.equinix.sdk.fabricv4.model.InternetAccessRoutingProtocolType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * InternetAccessRoutingProtocol
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class InternetAccessRoutingProtocol {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  protected InternetAccessRoutingProtocolType type;

  public static final String SERIALIZED_NAME_CUSTOMER_ROUTES = "customerRoutes";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ROUTES)
  @javax.annotation.Nonnull
  private List<InternetAccessCustomerRoute> customerRoutes = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONNECTIONS = "connections";
  @SerializedName(SERIALIZED_NAME_CONNECTIONS)
  @javax.annotation.Nonnull
  private List<InternetAccessConnection> connections = new ArrayList<>();

  public InternetAccessRoutingProtocol() {

  }

  public InternetAccessRoutingProtocol type(@javax.annotation.Nonnull InternetAccessRoutingProtocolType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public InternetAccessRoutingProtocolType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull InternetAccessRoutingProtocolType type) {
    this.type = type;
  }


  public InternetAccessRoutingProtocol customerRoutes(@javax.annotation.Nonnull List<InternetAccessCustomerRoute> customerRoutes) {
    this.customerRoutes = customerRoutes;
    return this;
  }

  public InternetAccessRoutingProtocol addCustomerRoutesItem(InternetAccessCustomerRoute customerRoutesItem) {
    if (this.customerRoutes == null) {
      this.customerRoutes = new ArrayList<>();
    }
    this.customerRoutes.add(customerRoutesItem);
    return this;
  }

  /**
   * Get customerRoutes
   * @return customerRoutes
   */
  @javax.annotation.Nonnull
  public List<InternetAccessCustomerRoute> getCustomerRoutes() {
    return customerRoutes;
  }

  public void setCustomerRoutes(@javax.annotation.Nonnull List<InternetAccessCustomerRoute> customerRoutes) {
    this.customerRoutes = customerRoutes;
  }


  public InternetAccessRoutingProtocol connections(@javax.annotation.Nonnull List<InternetAccessConnection> connections) {
    this.connections = connections;
    return this;
  }

  public InternetAccessRoutingProtocol addConnectionsItem(InternetAccessConnection connectionsItem) {
    if (this.connections == null) {
      this.connections = new ArrayList<>();
    }
    this.connections.add(connectionsItem);
    return this;
  }

  /**
   * Get connections
   * @return connections
   */
  @javax.annotation.Nonnull
  public List<InternetAccessConnection> getConnections() {
    return connections;
  }

  public void setConnections(@javax.annotation.Nonnull List<InternetAccessConnection> connections) {
    this.connections = connections;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternetAccessRoutingProtocol internetAccessRoutingProtocol = (InternetAccessRoutingProtocol) o;
    return Objects.equals(this.type, internetAccessRoutingProtocol.type) &&
        Objects.equals(this.customerRoutes, internetAccessRoutingProtocol.customerRoutes) &&
        Objects.equals(this.connections, internetAccessRoutingProtocol.connections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, customerRoutes, connections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternetAccessRoutingProtocol {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    customerRoutes: ").append(toIndentedString(customerRoutes)).append("\n");
    sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "customerRoutes", "connections"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type", "customerRoutes", "connections"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternetAccessRoutingProtocol
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternetAccessRoutingProtocol.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in InternetAccessRoutingProtocol is not found in the empty JSON string", InternetAccessRoutingProtocol.openapiRequiredFields.toString()));
        }
      }

      String discriminatorValue = jsonElement.getAsJsonObject().get("type").getAsString();
      switch (discriminatorValue) {
        case "BGP":
          InternetAccessRoutingProtocolBgp.validateJsonElement(jsonElement);
          break;
        case "DIRECT":
          InternetAccessRoutingProtocolDirect.validateJsonElement(jsonElement);
          break;
        case "STATIC":
          InternetAccessRoutingProtocolStatic.validateJsonElement(jsonElement);
          break;
        default:
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The value of the `type` field `%s` does not match any key defined in the discriminator's mapping.", discriminatorValue));
      }
  }


  /**
   * Create an instance of InternetAccessRoutingProtocol given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternetAccessRoutingProtocol
   * @throws IOException if the JSON string is invalid with respect to InternetAccessRoutingProtocol
   */
  public static InternetAccessRoutingProtocol fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternetAccessRoutingProtocol.class);
  }

  /**
   * Convert an instance of InternetAccessRoutingProtocol to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

