/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Action to perform on the LOA.
 */
@JsonAdapter(LoaActionType.Adapter.class)
public enum LoaActionType {
  
  ISSUER_AUTHORIZATION("LOA_ISSUER_AUTHORIZATION"),
  
  REQUESTOR_ACCEPTANCE("LOA_REQUESTOR_ACCEPTANCE"),
  
  COPY_LINK("LOA_COPY_LINK"),
  
  SEND_EMAIL_NOTIFICATION("LOA_SEND_EMAIL_NOTIFICATION"),
  
  CANCEL("LOA_CANCEL"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  LoaActionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LoaActionType fromValue(String value) {
    for (LoaActionType b : LoaActionType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<LoaActionType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LoaActionType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LoaActionType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LoaActionType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    LoaActionType.fromValue(value);
  }
}

