/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.equinix.sdk.fabricv4.model.LoaPatchPanelConnectorType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Specifies the demarcation point. &lt;br&gt; For CAGE_LOA - cageUniqueSpaceId is required. &lt;br&gt; For PATCH_PANEL_LOA - patchPanelId is required. &lt;br&gt; For PATCH_PANEL_PORT_LOA - patchPanelId, patchPanelPortA, patchPanelPortB      and connectorType is required. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class LoaDemarcationPoint {
  public static final String SERIALIZED_NAME_CAGE_UNIQUE_SPACE_ID = "cageUniqueSpaceId";
  @SerializedName(SERIALIZED_NAME_CAGE_UNIQUE_SPACE_ID)
  @javax.annotation.Nullable
  private String cageUniqueSpaceId;

  public static final String SERIALIZED_NAME_PATCH_PANEL_ID = "patchPanelId";
  @SerializedName(SERIALIZED_NAME_PATCH_PANEL_ID)
  @javax.annotation.Nullable
  private String patchPanelId;

  public static final String SERIALIZED_NAME_PATCH_PANEL_PORT_A = "patchPanelPortA";
  @SerializedName(SERIALIZED_NAME_PATCH_PANEL_PORT_A)
  @javax.annotation.Nullable
  private Integer patchPanelPortA;

  public static final String SERIALIZED_NAME_PATCH_PANEL_PORT_B = "patchPanelPortB";
  @SerializedName(SERIALIZED_NAME_PATCH_PANEL_PORT_B)
  @javax.annotation.Nullable
  private Integer patchPanelPortB;

  public static final String SERIALIZED_NAME_CONNECTOR_TYPE = "connectorType";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_TYPE)
  @javax.annotation.Nullable
  private LoaPatchPanelConnectorType connectorType;

  public LoaDemarcationPoint() {
  }

  public LoaDemarcationPoint cageUniqueSpaceId(@javax.annotation.Nullable String cageUniqueSpaceId) {
    this.cageUniqueSpaceId = cageUniqueSpaceId;
    return this;
  }

  /**
   * Unique identifier of the Cage.
   * @return cageUniqueSpaceId
   */
  @javax.annotation.Nullable
  public String getCageUniqueSpaceId() {
    return cageUniqueSpaceId;
  }

  public void setCageUniqueSpaceId(@javax.annotation.Nullable String cageUniqueSpaceId) {
    this.cageUniqueSpaceId = cageUniqueSpaceId;
  }


  public LoaDemarcationPoint patchPanelId(@javax.annotation.Nullable String patchPanelId) {
    this.patchPanelId = patchPanelId;
    return this;
  }

  /**
   * Unique identifier of the Patch Panel. 
   * @return patchPanelId
   */
  @javax.annotation.Nullable
  public String getPatchPanelId() {
    return patchPanelId;
  }

  public void setPatchPanelId(@javax.annotation.Nullable String patchPanelId) {
    this.patchPanelId = patchPanelId;
  }


  public LoaDemarcationPoint patchPanelPortA(@javax.annotation.Nullable Integer patchPanelPortA) {
    this.patchPanelPortA = patchPanelPortA;
    return this;
  }

  /**
   * Specify the desired port number. &lt;br&gt; When ports are not provided, next available ports will be used. 
   * @return patchPanelPortA
   */
  @javax.annotation.Nullable
  public Integer getPatchPanelPortA() {
    return patchPanelPortA;
  }

  public void setPatchPanelPortA(@javax.annotation.Nullable Integer patchPanelPortA) {
    this.patchPanelPortA = patchPanelPortA;
  }


  public LoaDemarcationPoint patchPanelPortB(@javax.annotation.Nullable Integer patchPanelPortB) {
    this.patchPanelPortB = patchPanelPortB;
    return this;
  }

  /**
   * Specify the desired port number. &lt;br&gt; When ports are not provided, next available ports will be used. &lt;br&gt; Required for Connector type FC and ST only. 
   * @return patchPanelPortB
   */
  @javax.annotation.Nullable
  public Integer getPatchPanelPortB() {
    return patchPanelPortB;
  }

  public void setPatchPanelPortB(@javax.annotation.Nullable Integer patchPanelPortB) {
    this.patchPanelPortB = patchPanelPortB;
  }


  public LoaDemarcationPoint connectorType(@javax.annotation.Nullable LoaPatchPanelConnectorType connectorType) {
    this.connectorType = connectorType;
    return this;
  }

  /**
   * Get connectorType
   * @return connectorType
   */
  @javax.annotation.Nullable
  public LoaPatchPanelConnectorType getConnectorType() {
    return connectorType;
  }

  public void setConnectorType(@javax.annotation.Nullable LoaPatchPanelConnectorType connectorType) {
    this.connectorType = connectorType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LoaDemarcationPoint instance itself
   */
  public LoaDemarcationPoint putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoaDemarcationPoint loaDemarcationPoint = (LoaDemarcationPoint) o;
    return Objects.equals(this.cageUniqueSpaceId, loaDemarcationPoint.cageUniqueSpaceId) &&
        Objects.equals(this.patchPanelId, loaDemarcationPoint.patchPanelId) &&
        Objects.equals(this.patchPanelPortA, loaDemarcationPoint.patchPanelPortA) &&
        Objects.equals(this.patchPanelPortB, loaDemarcationPoint.patchPanelPortB) &&
        Objects.equals(this.connectorType, loaDemarcationPoint.connectorType)&&
        Objects.equals(this.additionalProperties, loaDemarcationPoint.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cageUniqueSpaceId, patchPanelId, patchPanelPortA, patchPanelPortB, connectorType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoaDemarcationPoint {\n");
    sb.append("    cageUniqueSpaceId: ").append(toIndentedString(cageUniqueSpaceId)).append("\n");
    sb.append("    patchPanelId: ").append(toIndentedString(patchPanelId)).append("\n");
    sb.append("    patchPanelPortA: ").append(toIndentedString(patchPanelPortA)).append("\n");
    sb.append("    patchPanelPortB: ").append(toIndentedString(patchPanelPortB)).append("\n");
    sb.append("    connectorType: ").append(toIndentedString(connectorType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cageUniqueSpaceId", "patchPanelId", "patchPanelPortA", "patchPanelPortB", "connectorType"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to LoaDemarcationPoint
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LoaDemarcationPoint.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in LoaDemarcationPoint is not found in the empty JSON string", LoaDemarcationPoint.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cageUniqueSpaceId") != null && !jsonObj.get("cageUniqueSpaceId").isJsonNull()) && !jsonObj.get("cageUniqueSpaceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `cageUniqueSpaceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cageUniqueSpaceId").toString()));
      }
      if ((jsonObj.get("patchPanelId") != null && !jsonObj.get("patchPanelId").isJsonNull()) && !jsonObj.get("patchPanelId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `patchPanelId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("patchPanelId").toString()));
      }
      // validate the optional field `connectorType`
      if (jsonObj.get("connectorType") != null && !jsonObj.get("connectorType").isJsonNull()) {
        LoaPatchPanelConnectorType.validateJsonElement(jsonObj.get("connectorType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoaDemarcationPoint.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoaDemarcationPoint' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoaDemarcationPoint> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoaDemarcationPoint.class));

       return (TypeAdapter<T>) new TypeAdapter<LoaDemarcationPoint>() {
           @Override
           public void write(JsonWriter out, LoaDemarcationPoint value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LoaDemarcationPoint read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             LoaDemarcationPoint instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of LoaDemarcationPoint given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of LoaDemarcationPoint
   * @throws IOException if the JSON string is invalid with respect to LoaDemarcationPoint
   */
  public static LoaDemarcationPoint fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoaDemarcationPoint.class);
  }

  /**
   * Convert an instance of LoaDemarcationPoint to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

