/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Possible field names to use on sorting
 */
@JsonAdapter(RouteFilterRuleSortBy.Adapter.class)
public enum RouteFilterRuleSortBy {
  
  TYPE("/type"),
  
  UUID("/uuid"),
  
  NAME("/name"),
  
  STATE("/state"),
  
  PREFIX("/prefix"),
  
  PREFIXMATCH("/prefixMatch"),
  
  CHANGELOG_CREATEDDATETIME("/changeLog/createdDateTime"),
  
  CHANGELOG_UPDATEDDATETIME("/changeLog/updatedDateTime");

  private String value;

  RouteFilterRuleSortBy(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RouteFilterRuleSortBy fromValue(String value) {
    for (RouteFilterRuleSortBy b : RouteFilterRuleSortBy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RouteFilterRuleSortBy> {
    @Override
    public void write(final JsonWriter jsonWriter, final RouteFilterRuleSortBy enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RouteFilterRuleSortBy read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RouteFilterRuleSortBy.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    RouteFilterRuleSortBy.fromValue(value);
  }
}

