/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.sdk.fabricv4.model;

import java.util.Objects;
import com.equinix.sdk.fabricv4.model.StreamSubscriptionOperationErrors;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.equinix.sdk.fabricv4.JSON;

/**
 * Stream subscription operational information
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class StreamSubscriptionOperation {
  public static final String SERIALIZED_NAME_EVENTS_DELIVERED_COUNT = "eventsDeliveredCount";
  @SerializedName(SERIALIZED_NAME_EVENTS_DELIVERED_COUNT)
  @javax.annotation.Nullable
  private Integer eventsDeliveredCount;

  public static final String SERIALIZED_NAME_METRICS_DELIVERED_COUNT = "metricsDeliveredCount";
  @SerializedName(SERIALIZED_NAME_METRICS_DELIVERED_COUNT)
  @javax.annotation.Nullable
  private Integer metricsDeliveredCount;

  public static final String SERIALIZED_NAME_ALERTS_DELIVERED_COUNT = "alertsDeliveredCount";
  @SerializedName(SERIALIZED_NAME_ALERTS_DELIVERED_COUNT)
  @javax.annotation.Nullable
  private Integer alertsDeliveredCount;

  public static final String SERIALIZED_NAME_LAST_SUCCESSFUL_DELIVERY_DATE_TIME = "lastSuccessfulDeliveryDateTime";
  @SerializedName(SERIALIZED_NAME_LAST_SUCCESSFUL_DELIVERY_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime lastSuccessfulDeliveryDateTime;

  public static final String SERIALIZED_NAME_SUSPENDED_DATE_TIME = "suspendedDateTime";
  @SerializedName(SERIALIZED_NAME_SUSPENDED_DATE_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime suspendedDateTime;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  @javax.annotation.Nullable
  private List<StreamSubscriptionOperationErrors> errors = new ArrayList<>();

  public StreamSubscriptionOperation() {
  }

  public StreamSubscriptionOperation eventsDeliveredCount(@javax.annotation.Nullable Integer eventsDeliveredCount) {
    this.eventsDeliveredCount = eventsDeliveredCount;
    return this;
  }

  /**
   * count of delivered events
   * @return eventsDeliveredCount
   */
  @javax.annotation.Nullable
  public Integer getEventsDeliveredCount() {
    return eventsDeliveredCount;
  }

  public void setEventsDeliveredCount(@javax.annotation.Nullable Integer eventsDeliveredCount) {
    this.eventsDeliveredCount = eventsDeliveredCount;
  }


  public StreamSubscriptionOperation metricsDeliveredCount(@javax.annotation.Nullable Integer metricsDeliveredCount) {
    this.metricsDeliveredCount = metricsDeliveredCount;
    return this;
  }

  /**
   * count of delivered metrics
   * @return metricsDeliveredCount
   */
  @javax.annotation.Nullable
  public Integer getMetricsDeliveredCount() {
    return metricsDeliveredCount;
  }

  public void setMetricsDeliveredCount(@javax.annotation.Nullable Integer metricsDeliveredCount) {
    this.metricsDeliveredCount = metricsDeliveredCount;
  }


  public StreamSubscriptionOperation alertsDeliveredCount(@javax.annotation.Nullable Integer alertsDeliveredCount) {
    this.alertsDeliveredCount = alertsDeliveredCount;
    return this;
  }

  /**
   * count of delivered alerts
   * @return alertsDeliveredCount
   */
  @javax.annotation.Nullable
  public Integer getAlertsDeliveredCount() {
    return alertsDeliveredCount;
  }

  public void setAlertsDeliveredCount(@javax.annotation.Nullable Integer alertsDeliveredCount) {
    this.alertsDeliveredCount = alertsDeliveredCount;
  }


  public StreamSubscriptionOperation lastSuccessfulDeliveryDateTime(@javax.annotation.Nullable OffsetDateTime lastSuccessfulDeliveryDateTime) {
    this.lastSuccessfulDeliveryDateTime = lastSuccessfulDeliveryDateTime;
    return this;
  }

  /**
   * last successful date time of delivered event, metric, or alert
   * @return lastSuccessfulDeliveryDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastSuccessfulDeliveryDateTime() {
    return lastSuccessfulDeliveryDateTime;
  }

  public void setLastSuccessfulDeliveryDateTime(@javax.annotation.Nullable OffsetDateTime lastSuccessfulDeliveryDateTime) {
    this.lastSuccessfulDeliveryDateTime = lastSuccessfulDeliveryDateTime;
  }


  public StreamSubscriptionOperation suspendedDateTime(@javax.annotation.Nullable OffsetDateTime suspendedDateTime) {
    this.suspendedDateTime = suspendedDateTime;
    return this;
  }

  /**
   * suspended date time of stream subscription delivery for event, metric, or alert
   * @return suspendedDateTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSuspendedDateTime() {
    return suspendedDateTime;
  }

  public void setSuspendedDateTime(@javax.annotation.Nullable OffsetDateTime suspendedDateTime) {
    this.suspendedDateTime = suspendedDateTime;
  }


  public StreamSubscriptionOperation errors(@javax.annotation.Nullable List<StreamSubscriptionOperationErrors> errors) {
    this.errors = errors;
    return this;
  }

  public StreamSubscriptionOperation addErrorsItem(StreamSubscriptionOperationErrors errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * List of error information for stream subscription delivery
   * @return errors
   */
  @javax.annotation.Nullable
  public List<StreamSubscriptionOperationErrors> getErrors() {
    return errors;
  }

  public void setErrors(@javax.annotation.Nullable List<StreamSubscriptionOperationErrors> errors) {
    this.errors = errors;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the StreamSubscriptionOperation instance itself
   */
  public StreamSubscriptionOperation putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamSubscriptionOperation streamSubscriptionOperation = (StreamSubscriptionOperation) o;
    return Objects.equals(this.eventsDeliveredCount, streamSubscriptionOperation.eventsDeliveredCount) &&
        Objects.equals(this.metricsDeliveredCount, streamSubscriptionOperation.metricsDeliveredCount) &&
        Objects.equals(this.alertsDeliveredCount, streamSubscriptionOperation.alertsDeliveredCount) &&
        Objects.equals(this.lastSuccessfulDeliveryDateTime, streamSubscriptionOperation.lastSuccessfulDeliveryDateTime) &&
        Objects.equals(this.suspendedDateTime, streamSubscriptionOperation.suspendedDateTime) &&
        Objects.equals(this.errors, streamSubscriptionOperation.errors)&&
        Objects.equals(this.additionalProperties, streamSubscriptionOperation.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventsDeliveredCount, metricsDeliveredCount, alertsDeliveredCount, lastSuccessfulDeliveryDateTime, suspendedDateTime, errors, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamSubscriptionOperation {\n");
    sb.append("    eventsDeliveredCount: ").append(toIndentedString(eventsDeliveredCount)).append("\n");
    sb.append("    metricsDeliveredCount: ").append(toIndentedString(metricsDeliveredCount)).append("\n");
    sb.append("    alertsDeliveredCount: ").append(toIndentedString(alertsDeliveredCount)).append("\n");
    sb.append("    lastSuccessfulDeliveryDateTime: ").append(toIndentedString(lastSuccessfulDeliveryDateTime)).append("\n");
    sb.append("    suspendedDateTime: ").append(toIndentedString(suspendedDateTime)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("eventsDeliveredCount");
    openapiFields.add("metricsDeliveredCount");
    openapiFields.add("alertsDeliveredCount");
    openapiFields.add("lastSuccessfulDeliveryDateTime");
    openapiFields.add("suspendedDateTime");
    openapiFields.add("errors");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StreamSubscriptionOperation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StreamSubscriptionOperation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StreamSubscriptionOperation is not found in the empty JSON string", StreamSubscriptionOperation.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("errors") != null && !jsonObj.get("errors").isJsonNull()) {
        JsonArray jsonArrayerrors = jsonObj.getAsJsonArray("errors");
        if (jsonArrayerrors != null) {
          // ensure the json data is an array
          if (!jsonObj.get("errors").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `errors` to be an array in the JSON string but got `%s`", jsonObj.get("errors").toString()));
          }

          // validate the optional field `errors` (array)
          for (int i = 0; i < jsonArrayerrors.size(); i++) {
            StreamSubscriptionOperationErrors.validateJsonElement(jsonArrayerrors.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StreamSubscriptionOperation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StreamSubscriptionOperation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StreamSubscriptionOperation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StreamSubscriptionOperation.class));

       return (TypeAdapter<T>) new TypeAdapter<StreamSubscriptionOperation>() {
           @Override
           public void write(JsonWriter out, StreamSubscriptionOperation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public StreamSubscriptionOperation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             StreamSubscriptionOperation instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StreamSubscriptionOperation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StreamSubscriptionOperation
   * @throws IOException if the JSON string is invalid with respect to StreamSubscriptionOperation
   */
  public static StreamSubscriptionOperation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StreamSubscriptionOperation.class);
  }

  /**
   * Convert an instance of StreamSubscriptionOperation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

