/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EndCustomer
 */
public class EndCustomerTest {
    private final EndCustomer model = new EndCustomer();

    /**
     * Model tests for EndCustomer
     */
    @Test
    public void testEndCustomer() {
        // TODO: test EndCustomer
    }

    /**
     * Test the property 'isDisclosed'
     */
    @Test
    public void isDisclosedTest() {
        // TODO: test isDisclosed
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'mdmId'
     */
    @Test
    public void mdmIdTest() {
        // TODO: test mdmId
    }

}
