/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PrecisionTimeOrder
 */
public class PrecisionTimeOrderTest {
    private final PrecisionTimeOrder model = new PrecisionTimeOrder();

    /**
     * Model tests for PrecisionTimeOrder
     */
    @Test
    public void testPrecisionTimeOrder() {
        // TODO: test PrecisionTimeOrder
    }

    /**
     * Test the property 'purchaseOrderNumber'
     */
    @Test
    public void purchaseOrderNumberTest() {
        // TODO: test purchaseOrderNumber
    }

    /**
     * Test the property 'customerReferenceNumber'
     */
    @Test
    public void customerReferenceNumberTest() {
        // TODO: test customerReferenceNumber
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

}
