/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.equinix.services.fabricv4.model.Changelog;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PrecisionTimePackageResponse
 */
public class PrecisionTimePackageResponseTest {
    private final PrecisionTimePackageResponse model = new PrecisionTimePackageResponse();

    /**
     * Model tests for PrecisionTimePackageResponse
     */
    @Test
    public void testPrecisionTimePackageResponse() {
        // TODO: test PrecisionTimePackageResponse
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'bandwidth'
     */
    @Test
    public void bandwidthTest() {
        // TODO: test bandwidth
    }

    /**
     * Test the property 'clientsPerSecondMax'
     */
    @Test
    public void clientsPerSecondMaxTest() {
        // TODO: test clientsPerSecondMax
    }

    /**
     * Test the property 'redundancySupported'
     */
    @Test
    public void redundancySupportedTest() {
        // TODO: test redundancySupported
    }

    /**
     * Test the property 'multiSubnetSupported'
     */
    @Test
    public void multiSubnetSupportedTest() {
        // TODO: test multiSubnetSupported
    }

    /**
     * Test the property 'accuracySlaUnit'
     */
    @Test
    public void accuracySlaUnitTest() {
        // TODO: test accuracySlaUnit
    }

    /**
     * Test the property 'accuracySla'
     */
    @Test
    public void accuracySlaTest() {
        // TODO: test accuracySla
    }

    /**
     * Test the property 'accuracySlaMin'
     */
    @Test
    public void accuracySlaMinTest() {
        // TODO: test accuracySlaMin
    }

    /**
     * Test the property 'accuracySlaMax'
     */
    @Test
    public void accuracySlaMaxTest() {
        // TODO: test accuracySlaMax
    }

    /**
     * Test the property 'changelog'
     */
    @Test
    public void changelogTest() {
        // TODO: test changelog
    }

}
