/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.equinix.services.fabricv4.model.Changelog;
import com.equinix.services.fabricv4.model.DirectConnectionIpv4;
import com.equinix.services.fabricv4.model.DirectConnectionIpv6;
import com.equinix.services.fabricv4.model.RoutingProtocolChange;
import com.equinix.services.fabricv4.model.RoutingProtocolOperation;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RoutingProtocolDirectData
 */
public class RoutingProtocolDirectDataTest {
    private final RoutingProtocolDirectData model = new RoutingProtocolDirectData();

    /**
     * Model tests for RoutingProtocolDirectData
     */
    @Test
    public void testRoutingProtocolDirectData() {
        // TODO: test RoutingProtocolDirectData
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'directIpv4'
     */
    @Test
    public void directIpv4Test() {
        // TODO: test directIpv4
    }

    /**
     * Test the property 'directIpv6'
     */
    @Test
    public void directIpv6Test() {
        // TODO: test directIpv6
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'change'
     */
    @Test
    public void changeTest() {
        // TODO: test change
    }

    /**
     * Test the property 'changelog'
     */
    @Test
    public void changelogTest() {
        // TODO: test changelog
    }

}
