/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.equinix.services.fabricv4.model.PaginationRequest;
import com.equinix.services.fabricv4.model.ServiceTokenSearchExpression;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceTokenSearchRequest
 */
public class ServiceTokenSearchRequestTest {
    private final ServiceTokenSearchRequest model = new ServiceTokenSearchRequest();

    /**
     * Model tests for ServiceTokenSearchRequest
     */
    @Test
    public void testServiceTokenSearchRequest() {
        // TODO: test ServiceTokenSearchRequest
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

}
