/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SimplifiedNotification
 */
public class SimplifiedNotificationTest {
    private final SimplifiedNotification model = new SimplifiedNotification();

    /**
     * Model tests for SimplifiedNotification
     */
    @Test
    public void testSimplifiedNotification() {
        // TODO: test SimplifiedNotification
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'sendInterval'
     */
    @Test
    public void sendIntervalTest() {
        // TODO: test sendInterval
    }

    /**
     * Test the property 'emails'
     */
    @Test
    public void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'registeredUsers'
     */
    @Test
    public void registeredUsersTest() {
        // TODO: test registeredUsers
    }

}
