/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.equinix.services.fabricv4.model.SortBy;
import com.equinix.services.fabricv4.model.SortDirection;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SortCriteriaResponse
 */
public class SortCriteriaResponseTest {
    private final SortCriteriaResponse model = new SortCriteriaResponse();

    /**
     * Model tests for SortCriteriaResponse
     */
    @Test
    public void testSortCriteriaResponse() {
        // TODO: test SortCriteriaResponse
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'property'
     */
    @Test
    public void propertyTest() {
        // TODO: test property
    }

}
