/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.services.fabricv4.model;

import com.equinix.services.fabricv4.model.VirtualConnectionPriceZSideAccessPointBridgePackage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VirtualConnectionPriceZSideAccessPointBridge
 */
public class VirtualConnectionPriceZSideAccessPointBridgeTest {
    private final VirtualConnectionPriceZSideAccessPointBridge model = new VirtualConnectionPriceZSideAccessPointBridge();

    /**
     * Model tests for VirtualConnectionPriceZSideAccessPointBridge
     */
    @Test
    public void testVirtualConnectionPriceZSideAccessPointBridge() {
        // TODO: test VirtualConnectionPriceZSideAccessPointBridge
    }

    /**
     * Test the property '_package'
     */
    @Test
    public void _packageTest() {
        // TODO: test _package
    }

}
