/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NetworkChangeType
 */
public class NetworkChangeTypeTest {
    /**
     * Model tests for NetworkChangeType
     */
    @Test
    public void testNetworkChangeType() {
        // TODO: test NetworkChangeType
    }

}
