/*
 * Equinix Fabric API v4
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.fabric.v4.model;

import com.equinix.openapi.fabric.v4.model.BandwidthUtilization;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Statistics
 */
public class StatisticsTest {
    private final Statistics model = new Statistics();

    /**
     * Model tests for Statistics
     */
    @Test
    public void testStatistics() {
        // TODO: test Statistics
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'viewPoint'
     */
    @Test
    public void viewPointTest() {
        // TODO: test viewPoint
    }

    /**
     * Test the property 'bandwidthUtilization'
     */
    @Test
    public void bandwidthUtilizationTest() {
        // TODO: test bandwidthUtilization
    }

}
